use v6;
#  -- DO NOT EDIT --
# generated by css-gen-properties.pl --role=CSS::Language::CSS3::Backgrounds_and_Borders::Spec::Interface etc/css3x-background-20120724.txt
role CSS::Language::CSS3::Backgrounds_and_Borders::Spec::Interface {
    method attachment($/) { ... }
    method bg-image($/) { ... }
    method bg-layer($/) { ... }
    method bg-size($/) { ... }
    method border-style($/) { ... }
    method border-width($/) { ... }
    method box($/) { ... }
    method color($/) { ... }
    method final-bg-layer($/) { ... }
    method image($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method position($/) { ... }
    method repeat-style($/) { ... }
    method shadow($/) { ... }
}
