use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS3::Backgrounds_and_Borders::Spec::Actions {
    method expr-border-image-outset($/) { make $.list($/) }
    method expr-border-image-repeat($/) { make $.list($/) }
    method expr-border-image-slice($/) { make $.list($/) }
    method expr-border-image-source($/) { make $.list($/) }
    method expr-border-image-width($/) { make $.list($/) }
    method expr-border-style($/) { make $.list($/) }
    method expr-border-top-style($/) { make $.list($/) }
    method expr-border-right-style($/) { make $.list($/) }
    method expr-border-bottom-style($/) { make $.list($/) }
    method expr-border-left-style($/) { make $.list($/) }
    method expr-border-top-width($/) { make $.list($/) }
    method expr-border-right-width($/) { make $.list($/) }
    method expr-border-bottom-width($/) { make $.list($/) }
    method expr-border-left-width($/) { make $.list($/) }
    method expr-border-width($/) { make $.list($/) }
}
