use v6;
#  -- DO NOT EDIT --
# generated by: make_properties.pl 

class CSS::Module::CSS3::Backgrounds_and_Borders::Spec::Actions {
    method expr-border-image-outset($/) { make $.list($/) }
    method expr-border-image-repeat($/) { make $.list($/) }
    method expr-border-image-slice($/) { make $.list($/) }
    method expr-border-image-source($/) { make $.list($/) }
    method expr-border-image-width($/) { make $.list($/) }
    method expr-border-style($/) { make $.list($/) }
    method expr-border-width($/) { make $.list($/) }
}
