use v6;
#  -- DO NOT EDIT --
# generated by: css-gen-properties.pl --grammar=CSS::Module::CSS3::Backgrounds_and_Borders::Spec::Grammar --proforma etc/css3x-background-20120724.txt

grammar CSS::Module::CSS3::Backgrounds_and_Borders::Spec::Grammar {

    #| background: [ <bg-layer> , ]* <final-bg-layer>
    rule decl:sym<background> {:i (background) ':'  [ <proforma> || <expr=.expr-background> || <any-args> ] }
    rule expr-background {:i [ <bg-layer> ',' ]* <final-bg-layer> }

    #| background-attachment: <attachment> [ , <attachment> ]*
    rule decl:sym<background-attachment> {:i (background\-attachment) ':'  [ <proforma> || <expr=.expr-background-attachment> || <any-args> ] }
    rule expr-background-attachment {:i <attachment> [ ',' <attachment> ]* }

    #| background-clip: <box> [ , <box> ]*
    rule decl:sym<background-clip> {:i (background\-clip) ':'  [ <proforma> || <expr=.expr-background-clip> || <any-args> ] }
    rule expr-background-clip {:i <box> [ ',' <box> ]* }

    #| background-color: <color>
    rule decl:sym<background-color> {:i (background\-color) ':'  [ <proforma> || <expr=.expr-background-color> || <any-args> ] }
    rule expr-background-color {:i <color> }

    #| background-image: <bg-image> [ , <bg-image> ]*
    rule decl:sym<background-image> {:i (background\-image) ':'  [ <proforma> || <expr=.expr-background-image> || <any-args> ] }
    rule expr-background-image {:i <bg-image> [ ',' <bg-image> ]* }

    #| background-origin: <box> [ , <box> ]*
    rule decl:sym<background-origin> {:i (background\-origin) ':'  [ <proforma> || <expr=.expr-background-origin> || <any-args> ] }
    rule expr-background-origin {:i <box> [ ',' <box> ]* }

    #| background-position: <position> [ , <position> ]*
    rule decl:sym<background-position> {:i (background\-position) ':'  [ <proforma> || <expr=.expr-background-position> || <any-args> ] }
    rule expr-background-position {:i <position> [ ',' <position> ]* }

    #| background-repeat: <repeat-style> [ , <repeat-style> ]*
    rule decl:sym<background-repeat> {:i (background\-repeat) ':'  [ <proforma> || <expr=.expr-background-repeat> || <any-args> ] }
    rule expr-background-repeat {:i <repeat-style> [ ',' <repeat-style> ]* }

    #| background-size: <bg-size> [ , <bg-size> ]*
    rule decl:sym<background-size> {:i (background\-size) ':'  [ <proforma> || <expr=.expr-background-size> || <any-args> ] }
    rule expr-background-size {:i <bg-size> [ ',' <bg-size> ]* }

    #| border: <border-width> || <border-style> || <color>
    rule decl:sym<border> {:i (border) ':'  [ <proforma> || <expr=.expr-border> || <any-args> ] }
    rule expr-border {:i [:my @*SEEN; <border-width> <!seen(0)> | <border-style> <!seen(1)> | <color> <!seen(2)> ]+ }

    #| border-color: <color>{1,4}
    rule decl:sym<border-color> {:i (border\-color) ':'  [ <proforma> || <expr=.expr-border-color>**1..4 || <any-args> ] }
    rule expr-border-color {:i <color> }

    #| border-image: <‘border-image-source’> || <‘border-image-slice’> [ / <‘border-image-width’> | / <‘border-image-width’>? / <‘border-image-outset’> ]? || <‘border-image-repeat’>
    rule decl:sym<border-image> {:i (border\-image) ':'  [ <proforma> || <expr=.expr-border-image> || <any-args> ] }
    rule expr-border-image {:i [:my @*SEEN; <expr-border-image-source> <!seen(0)> | <expr-border-image-slice> [ [ '/' <expr-border-image-width> | '/' <expr-border-image-width>? '/' <expr-border-image-outset> ] ]? <!seen(1)> | <expr-border-image-repeat> <!seen(2)> ]+ }

    #| border-image-outset: [ <length> | <number> ]{1,4}
    rule decl:sym<border-image-outset> {:i (border\-image\-outset) ':'  [ <proforma> || <expr=.expr-border-image-outset>**1..4 || <any-args> ] }
    rule expr-border-image-outset {:i [ [ <length> | <number> ] ] }

    #| border-image-repeat: [ stretch | repeat | round | space ]{1,2}
    rule decl:sym<border-image-repeat> {:i (border\-image\-repeat) ':'  [ <proforma> || <expr=.expr-border-image-repeat> || <any-args> ] }
    rule expr-border-image-repeat {:i [ [ stretch | repeat | round | space ] & <keyw> ]**1..2 }

    #| border-image-slice: [<number> | <percentage>]{1,4} && fill?
    rule decl:sym<border-image-slice> {:i (border\-image\-slice) ':'  [ <proforma> || <expr=.expr-border-image-slice> || <any-args> ] }
    rule expr-border-image-slice {:i [:my @*SEEN; [ [ <number> | <percentage> ] ]**1..4 <!seen(0)> | [ fill & <keyw> ]? <!seen(1)> ]**2 }

    #| border-image-source: none | <image>
    rule decl:sym<border-image-source> {:i (border\-image\-source) ':'  [ <proforma> || <expr=.expr-border-image-source> || <any-args> ] }
    rule expr-border-image-source {:i [ none & <keyw> | <image> ] }

    #| border-image-width: [ <length> | <percentage> | <number> | auto ]{1,4}
    rule decl:sym<border-image-width> {:i (border\-image\-width) ':'  [ <proforma> || <expr=.expr-border-image-width>**1..4 || <any-args> ] }
    rule expr-border-image-width {:i [ [ <length> | <percentage> | <number> | auto & <keyw> ] ] }

    #| border-radius: [ <length> | <percentage> ]{1,4} [ / [ <length> | <percentage> ]{1,4} ]?
    rule decl:sym<border-radius> {:i (border\-radius) ':'  [ <proforma> || <expr=.expr-border-radius> || <any-args> ] }
    rule expr-border-radius {:i [ [ <length> | <percentage> ] ]**1..4 [ '/' [ [ <length> | <percentage> ] ]**1..4 ]? }

    #| border-style: <border-style>{1,4}
    rule decl:sym<border-style> {:i (border\-style) ':'  [ <proforma> || <expr=.expr-border-style>**1..4 || <any-args> ] }
    rule expr-border-style {:i <border-style> }

    #| border-top: <border-width> || <border-style> || <color>
    rule decl:sym<border-top> {:i (border\-top) ':'  [ <proforma> || <expr=.expr-border-top> || <any-args> ] }
    rule expr-border-top {:i [:my @*SEEN; <border-width> <!seen(0)> | <border-style> <!seen(1)> | <color> <!seen(2)> ]+ }

    #| border-right: <border-width> || <border-style> || <color>
    rule decl:sym<border-right> {:i (border\-right) ':'  [ <proforma> || <expr=.expr-border-right> || <any-args> ] }
    rule expr-border-right {:i [:my @*SEEN; <border-width> <!seen(0)> | <border-style> <!seen(1)> | <color> <!seen(2)> ]+ }

    #| border-bottom: <border-width> || <border-style> || <color>
    rule decl:sym<border-bottom> {:i (border\-bottom) ':'  [ <proforma> || <expr=.expr-border-bottom> || <any-args> ] }
    rule expr-border-bottom {:i [:my @*SEEN; <border-width> <!seen(0)> | <border-style> <!seen(1)> | <color> <!seen(2)> ]+ }

    #| border-left: <border-width> || <border-style> || <color>
    rule decl:sym<border-left> {:i (border\-left) ':'  [ <proforma> || <expr=.expr-border-left> || <any-args> ] }
    rule expr-border-left {:i [:my @*SEEN; <border-width> <!seen(0)> | <border-style> <!seen(1)> | <color> <!seen(2)> ]+ }

    #| border-top-color: <color>
    rule decl:sym<border-top-color> {:i (border\-top\-color) ':'  [ <proforma> || <expr=.expr-border-top-color> || <any-args> ] }
    rule expr-border-top-color {:i <color> }

    #| border-right-color: <color>
    rule decl:sym<border-right-color> {:i (border\-right\-color) ':'  [ <proforma> || <expr=.expr-border-right-color> || <any-args> ] }
    rule expr-border-right-color {:i <color> }

    #| border-bottom-color: <color>
    rule decl:sym<border-bottom-color> {:i (border\-bottom\-color) ':'  [ <proforma> || <expr=.expr-border-bottom-color> || <any-args> ] }
    rule expr-border-bottom-color {:i <color> }

    #| border-left-color: <color>
    rule decl:sym<border-left-color> {:i (border\-left\-color) ':'  [ <proforma> || <expr=.expr-border-left-color> || <any-args> ] }
    rule expr-border-left-color {:i <color> }

    #| border-top-left-radius: [ <length> | <percentage> ]{1,2}
    rule decl:sym<border-top-left-radius> {:i (border\-top\-left\-radius) ':'  [ <proforma> || <expr=.expr-border-top-left-radius> || <any-args> ] }
    rule expr-border-top-left-radius {:i [ [ <length> | <percentage> ] ]**1..2 }

    #| border-top-right-radius: [ <length> | <percentage> ]{1,2}
    rule decl:sym<border-top-right-radius> {:i (border\-top\-right\-radius) ':'  [ <proforma> || <expr=.expr-border-top-right-radius> || <any-args> ] }
    rule expr-border-top-right-radius {:i [ [ <length> | <percentage> ] ]**1..2 }

    #| border-bottom-right-radius: [ <length> | <percentage> ]{1,2}
    rule decl:sym<border-bottom-right-radius> {:i (border\-bottom\-right\-radius) ':'  [ <proforma> || <expr=.expr-border-bottom-right-radius> || <any-args> ] }
    rule expr-border-bottom-right-radius {:i [ [ <length> | <percentage> ] ]**1..2 }

    #| border-bottom-left-radius: [ <length> | <percentage> ]{1,2}
    rule decl:sym<border-bottom-left-radius> {:i (border\-bottom\-left\-radius) ':'  [ <proforma> || <expr=.expr-border-bottom-left-radius> || <any-args> ] }
    rule expr-border-bottom-left-radius {:i [ [ <length> | <percentage> ] ]**1..2 }

    #| border-top-style: <border-style>
    rule decl:sym<border-top-style> {:i (border\-top\-style) ':'  [ <proforma> || <expr=.expr-border-top-style> || <any-args> ] }
    rule expr-border-top-style {:i <border-style> }

    #| border-right-style: <border-style>
    rule decl:sym<border-right-style> {:i (border\-right\-style) ':'  [ <proforma> || <expr=.expr-border-right-style> || <any-args> ] }
    rule expr-border-right-style {:i <border-style> }

    #| border-bottom-style: <border-style>
    rule decl:sym<border-bottom-style> {:i (border\-bottom\-style) ':'  [ <proforma> || <expr=.expr-border-bottom-style> || <any-args> ] }
    rule expr-border-bottom-style {:i <border-style> }

    #| border-left-style: <border-style>
    rule decl:sym<border-left-style> {:i (border\-left\-style) ':'  [ <proforma> || <expr=.expr-border-left-style> || <any-args> ] }
    rule expr-border-left-style {:i <border-style> }

    #| border-top-width: <border-width>
    rule decl:sym<border-top-width> {:i (border\-top\-width) ':'  [ <proforma> || <expr=.expr-border-top-width> || <any-args> ] }
    rule expr-border-top-width {:i <border-width> }

    #| border-right-width: <border-width>
    rule decl:sym<border-right-width> {:i (border\-right\-width) ':'  [ <proforma> || <expr=.expr-border-right-width> || <any-args> ] }
    rule expr-border-right-width {:i <border-width> }

    #| border-bottom-width: <border-width>
    rule decl:sym<border-bottom-width> {:i (border\-bottom\-width) ':'  [ <proforma> || <expr=.expr-border-bottom-width> || <any-args> ] }
    rule expr-border-bottom-width {:i <border-width> }

    #| border-left-width: <border-width>
    rule decl:sym<border-left-width> {:i (border\-left\-width) ':'  [ <proforma> || <expr=.expr-border-left-width> || <any-args> ] }
    rule expr-border-left-width {:i <border-width> }

    #| border-width: <border-width>{1,4}
    rule decl:sym<border-width> {:i (border\-width) ':'  [ <proforma> || <expr=.expr-border-width>**1..4 || <any-args> ] }
    rule expr-border-width {:i <border-width> }

    #| box-decoration-break: slice | clone
    rule decl:sym<box-decoration-break> {:i (box\-decoration\-break) ':'  [ <proforma> || <expr=.expr-box-decoration-break> || <any-args> ] }
    rule expr-box-decoration-break {:i [ slice | clone ] & <keyw> }

    #| box-shadow: none | <shadow> [ , <shadow> ]*
    rule decl:sym<box-shadow> {:i (box\-shadow) ':'  [ <proforma> || <expr=.expr-box-shadow> || <any-args> ] }
    rule expr-box-shadow {:i [ none & <keyw> | <shadow> [ ',' <shadow> ]* ] }
}
