use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 
role CSS::Module::CSS3::Backgrounds_and_Borders::Spec::Interface {
    method bg-layer($/) { ... }
    method box($/) { ... }
    method color($/) { ... }
    method final-bg-layer($/) { ... }
    method image($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method position($/) { ... }
    method shadow($/) { ... }
}
